### ISSUE TITLE
关于在arm_car和arm_static中的两行代码的问题

### ISSUE THREAD

**Issue by DickyNJ** [Alcatraz1337/DUT-COMI-ROS#14]
中arm_car和arm_static中的init方法的以下两句代码我不确定是否可以这样用，我想的是在初始化时给 ArmStatus的状态置为False，返回是置为True
self._msg = ArmStatus()
self._msg.status = False # 机械臂的状态初始化为False

**Comment by Alcatraz1337** [comment]
这么写没问题 #13
